name: Generate Docs

on:
  push:
    branches:
      - main

jobs:
  cargo_doc:
    name: Cargo Doc
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write
      pages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Rustup & Docs
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          components: rust-docs
      - name: Generate Docs
        run: cargo doc --no-deps --all-features
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/doc
